name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted   # since you started your own runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
      
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      # ⚠️ apply only if you really want auto-deploy
      - name: Terraform Apply
        run: terraform apply -auto-approve