name: terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
          path: /u02/stage/oracle-rac

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform
        run: |
          cd ./terraform
          pwd
          ls -la
          terraform init
          terraform plan
          terraform apply -auto-approve
        