name: terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Structure
        run: |
          echo "Current Dir:"
          pwd
          echo "Root files:"
          ls -la
          echo "Terraform folder:"
          ls -la terraform || echo "terraform folder missing"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform
        run: |
          cd terraform
          pwd
          ls -la
          terraform init
          terraform plan
          terraform apply -auto-approve
        working-directory: ./terraform/