name: Terraform Hyper-V Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /oracle-rac/oracle-rac/terraform   # IMPORTANT FIX

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        working-directory: /oracle-rac/oracle-rac/terraform
        run: terraform apply -auto-approve